const artProjects = [
    {
      title: "Lavender Dancer",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/dancer.png",
      link: "art/",
    },
    {
      title: "Colour Bubble",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/horn.png",
      link: "art/",
    },
    {
      title: "Spirit of the Forest",
      materials: "Acrylic on Canvas",
      description: "Some of my miscellaneous sketches.",
      image: "/art/forest1.png",
      link: "art/",
    },
    {
      title: "Blossoming Tree",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/tree.png",
      link: "art/",
    },

    {
      title: "Self Portrait - Summer 2025",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/self3.png",
      link: "art/",
    },
    {
      title: "Starry day",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/starry.png",
      link: "art/",
    },
    {
      title: "The Line Drawn",
      materials: "Watercolour and Thread on Watercolour Paper, and Acrylic on Acrylic",
      description: "Some of my miscellaneous sketches.",
      image: "/art/media2.png",
      link: "art/",
    },
    {
      title: "Polar",
      materials: "Acrylic on Shower Curtain",
      description: "Some of my miscellaneous sketches.",
      image: "/art/polar4.png",
      link: "art/",
    },
    {
      title: "The Watcher",
      materials: "Acrylic on Canvas",
      description: "Some of my miscellaneous sketches.",
      image: "/art/watcher9.png",
      link: "art/",
    },
    {
      title: "Blood",
      materials: "Alcohol Marker on Watercolour Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/blood.png",
      link: "art/",
    },
    {
      title: "Stormy Seas",
      materials: "Collage",
      description: "Sailing, with all its ups and downs.",
      image: "/art/collage2.png",
      link: "",
    },
    {
      title: "The Walk",
      materials: "Acrylic, Dish soap, and Crayon on Posterboard",
      description: "A depiction of the components of my daily subconscious.",
      image: "/art/walk13.png",
    },
    {
      title: "Candy Rush",
      materials: "Digital Painting",
      description: "Cover art for the song.",
      image: "/art/candy_rush.png",
    },
    {
      title: "By the Seaside",
      materials: "Digital Painting",
      description: "A drawing just for fun.",
      image: "/art/bythesea1.jpeg",
    },
    {
      title: "Bag of Bones",
      materials: "Divination Game with bones, tea, and a velvet bag",
      description: "A game to predict an uncertain future.",
      image: "/art/bones17.png",
    },
    {
      title: "Sketches",
      materials: "Pencil on Paper",
      description: "Some of my miscellaneous sketches.",
      image: "/art/sketch3.png",
      link: "art/",
    },
    {
      title: "Journal (2008)",
      materials: "Washable Marker on Paper",
      description: "A Journal from childhood.",
      image: "/art/journal1.png",
      link: "art/",
    },
    {
      title: "HairDye",
      materials: "Alcohol Marker on Paper",
      description: "A Journal from childhood.",
      image: "/art/collab.png",
      link: "art/",
    },
    {
      title: "MoonWater",
      materials: "Water, a Silver Goblet, and Crystals",
      description: "A Journal from childhood.",
      image: "/art/goblet1.png",
      link: "art/",
    },
    {
      title: "Tall Ladder",
      materials: "Pencil on Paper",
      description: "A Journal from childhood.",
      image: "/art/ladder2.png",
      link: "art/",
    },
    {
      title: "Too Late",
      materials: "Acrylic on Canvas",
      description: "A Journal from childhood.",
      image: "/art/memory.png",
      link: "art/",
    },
    {
      title: "Corner Store",
      materials: "Pencil and Charcoal on PosterBoard",
      description: "A Journal from childhood.",
      image: "/art/mirror1.png",
      link: "art/",
    },
    {
      title: "Pink Shell Necklace",
      materials: "Beads and Elastic",
      description: "A Journal from childhood.",
      image: "/art/necklace.png",
      link: "art/",
    },
    {
      title: "Pickle",
      materials: "Pencil on Paper",
      description: "A Journal from childhood.",
      image: "/art/pickle2.png",
      link: "art/",
    },
    {
      title: "MoonWater",
      materials: "Water, a Silver Goblet, and Crystals",
      description: "A Journal from childhood.",
      image: "/art/goblet1.png",
      link: "art/",
    },
];
export default artProjects;